# Generated by Django 2.2.26 on 2022-01-17 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_profile_rol'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='rol',
            field=models.CharField(choices=[('M', 'MEDICO'), ('A', 'ADMINISTRADOR')], default='M', max_length=1),
        ),
    ]
