# Generated by Django 2.2.26 on 2022-01-08 21:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Imagen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('pathImage', models.CharField(max_length=400)),
                ('date_upload', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(max_length=4000)),
                ('status', models.CharField(max_length=1)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.Profile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('title',),
            },
        ),
    ]
