# Generated by Django 2.2.26 on 2022-01-08 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Prediccion', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prediccion',
            options={'ordering': ('title',)},
        ),
    ]
