# Generated by Django 2.2.26 on 2022-01-20 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Prediccion', '0002_auto_20220108_1659'),
    ]

    operations = [
        migrations.AddField(
            model_name='prediccion',
            name='estado',
            field=models.CharField(choices=[('A', 'APROBADO'), ('R', 'RECHAZADO')], default='M', max_length=1),
        ),
    ]
